version: "3.8"
services:
    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./app:/var/www/html
        depends_on:
            - db
        networks:
            - lamp-network
    db:
        image: mysql:8.0
        container_name: lamp-mysql
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: musicex
            MYSQL_ROOT_PASSWORD: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        volumes:
            - ./docker/dump:/docker-entrypoint-initdb.d
            - ./docker/conf:/etc/mysql/conf.d
            - db_data:/var/lib/mysql
        networks:
            - lamp-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: lamp-phpmyadmin
        depends_on: 
            - db
        networks:
            - lamp-network
        ports:
            - 8900:80
        
        environment:
            MYSQL_USER: lamp
            MYSQL_PASSWORD: lamp
            MYSQL_ROOT_PASSWORD: test 
volumes:
    db_data: 
       driver: local

networks:
    lamp-network:
        driver: bridge